cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

dark_web/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.auth.views import LogoutView
from django.conf.urls.static import static
from django.conf.urls import url
from django.views.generic import RedirectView
from accounts import views as account_views
from vendor import views as vendor_views
from main import views as product_views

urlpatterns = [
    path('alibaba/', admin.site.urls),
    path('support/', include('support.urls')),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^signup/$', account_views.signup, name='signup'),
    url(r'^signin/$', account_views.LoginView.as_view(), name='signin'),
    url(r'^signin/gpg_auth/$', account_views.gpg_auth, name='gpg_auth'),
    url(r'^signin/gpg_verify/$', account_views.gpg_verify, name='gpg_verify'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^accounts/login/$', RedirectView.as_view(url='/signin')),
    url(r'^profile/update_tfalogin', account_views.update_tfalogin, name='update_tfalogin'),
    # Vendor Urls
    url(r'^vendor/add_product', vendor_views.add_product, name='user_vendor_add_product'),
    url(r'^vendor/save_product', vendor_views.save_product, name='user_vendor_save_product'),
    url(r'^vendor/delete_product/(?P<product_id>\d+)/$', vendor_views.delete_product, name='user_vendor_delete_product'),
    url(r'^vendor/edit_product/(?P<product_id>\d+)/$', vendor_views.edit_product, name='user_vendor_edit_product'),
    url(r'^vendor/shipping_options/(?P<shipping_option_id>\d+)/$', vendor_views.edit_shippingoption, name='shipping_options'),
    url(r'^vendor/shipping_options/$', vendor_views.shipping_options, name='shipping_options'), 
    url(r'^vendor/update_product/$', vendor_views.update_product, name='user_vendor_updateProduct'),
    url(r'^vendor/list_products', vendor_views.list_products, name='user_vendor_listProducts'),
    url(r'^vendor_profile/(?P<id>\d+)/', account_views.vendor_profile, name='vendor_profile'),
    url(r'^vendor_public_profile/(?P<id>\d+)/', account_views.vendor_public_profile, name='vendor_public_profile'),
    url(r'^vendor/newOrders/$', vendor_views.VendorNewOrderListView.as_view(), name='vendor_list_new_order'),
    url(r'^vendor/newOrders/(?P<order_id>\d+)/$', vendor_views.VendorNewOrderDetailView.as_view(), name='vendor_detail_new_order'),
    url(r'^vendor/shipOrders/$', vendor_views.VendorShippedOrderListView.as_view(), name='vendor_list_ship_order'),
    url(r'^vendor/shipOrders/(?P<order_id>\d+)/$', vendor_views.VendorShippedOrderDetailView.as_view(), name='vendor_detail_ship_order'),
    url(r'^vendor/completeOrders/$', vendor_views.VendorCompleteOrderListView.as_view(), name='vendor_list_complete_order'),
    url(r'^vendor/completeOrders/(?P<order_id>\d+)/$', vendor_views.VendorCompleteOrderDetailView.as_view(), name='vendor_detail_complete_order'),
    url(r'^vendor/cancelOrders/$', vendor_views.VendorCancelOrderListView.as_view(), name='vendor_list_cancel_order'),
    url(r'^vendor/cancelOrders/(?P<order_id>\d+)/$', vendor_views.VendorCancelOrderDetailView.as_view(), name='vendor_detail_cancel_order'),
    url(r'^vendor/disputeOrders/$', vendor_views.VendorDisputeOrderListView.as_view(), name='vendor_list_dispute_order'),
    url(r'^vendor/disputeOrders/(?P<order_id>\d+)/$', vendor_views.VendorDisputeOrderDetailView.as_view(), name='vendor_detail_dispute_order'),
    url(r'^vendor/acceptOrder/(?P<order_id>\d+)/$', vendor_views.accept_order, name='vendor_accept_order'),
    url(r'^vendor/rejectOrder/(?P<order_id>\d+)/$', vendor_views.reject_order, name='vendor_reject_order'),

    # Search url
    url(r'^search/$', product_views.search, name='search'),
    # path('accounts/', include('django.contrib.auth.urls')),

    url(r'^messages/$', product_views.UserMessageListView.as_view(), name='message_list'),

    # Inbox url
    url(r'^inbox/$', product_views.UserInboxListView.as_view(), name='inbox_list'),
    url(r'^inbox/(?P<message_id>\d+)/delete/$', product_views.delete_message, name='inbox_delete_message'),
    url(r'^inbox/send/$', product_views.inbox_send, name='inbox_send'),
    url(r'^inbox/send/(?P<receiver_id>\d+)/$', product_views.inbox_send, name='inbox_send'),

    path('account/', include('accounts.urls')),
    url(r'^accounts/$', RedirectView.as_view(url='/account')),  # Redirects url "/accounts" to "/account"

    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('background/', include('background.urls')),
    path('', include('main.urls')),
    # Star Rating Url
    url(r'^ratings/', include('star_ratings.urls', namespace='ratings')),

    # Avatar
    url(r'^avatar/', include('avatar.urls')),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    import debug_toolbar
    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),

                      # For django versions before 2.0:
                      # url(r'^__debug__/', include(debug_toolbar.urls)),

                  ] + urlpatterns

main/urls.py
from django.urls import path
from django.conf.urls import url
from . import views as views
from main import views as main_views
from . import views

urlpatterns = [
    url(r'^$', views.product_list, name='product_list'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
]

main/models.py
from django.db import models
from django.urls import reverse
from django_countries.fields import CountryField
from accounts.models import User
from star_ratings.models import Rating, UserRating
from django.core.validators import MaxValueValidator, MinValueValidator
from django.contrib.contenttypes.fields import GenericRelation
from django.template.defaultfilters import slugify

class Category(models.Model):
    name = models.CharField(max_length=150, db_index=True)
    slug = models.SlugField(max_length=150, unique=True ,db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name', )
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('product_list_by_category', args=[self.slug])


class Message(models.Model):
    sender = models.ForeignKey(User, related_name='message_sender', on_delete=models.CASCADE)
    receiver = models.ForeignKey(User, related_name='message_receiver', on_delete=models.CASCADE)
    content = models.TextField(default='')
    create = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)
    check = models.BooleanField(default=False)
    sender_removed = models.BooleanField(default=False)
    receiver_removed = models.BooleanField(default=False)

    def get_sender(self):
        return self.sender

    def get_receiver(self):
        return self.receiver


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, db_index=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, validators=[MinValueValidator(1.0)])
    available = models.BooleanField(default=True)
    stock = models.PositiveIntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    country = CountryField(null=True)
    productOwnerID = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Owner ID', editable=False, default=1)
    payout_address = models.CharField(max_length=100, default='')
    ratings = GenericRelation(Rating, related_query_name='products')

    class Meta:
        ordering = ('name', )
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
            return reverse('product_detail', args=[self.id, self.slug])


class ShippingOptions(models.Model):
    """docstring for ShippingOptions"""
    zone_name = models.CharField(max_length=100)
    zone_type = models.CharField(max_length=255)
    
    class Meta:
        ordering = ('id',)
    def __str__(self):
        return self.zone_name
        

main/views.py
from cart.forms import CartAddProductForm
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView
from django.shortcuts import render, get_object_or_404, redirect

from .models import Category, Product, Message
from django_countries import countries
from accounts.models import User, VendorTerm
from accounts.forms import LoginForm
from django.db.models import Q
from django.db.models import Avg, Sum

from django.template.defaulttags import register
from background.views import crypto_currencies


@register.filter
def get(dictionary, key):
    return dictionary.get(key)


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    message = len(Message.objects.filter(check=False))
    #message = len(Message.objects.all())
    form = LoginForm
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(category=category)

    #cryptocurrenies Data
    crypto_data = crypto_currencies()

    ratings = {}
    sold_cnt = {}
    for product in products:
        rating_total = 0
        rating_count = 0
        for order_item in product.order_items.filter(order__paid='8'):
            for rating in order_item.ratings.all():
                rating_total += rating.total * order_item.quantity
                rating_count += rating.count * order_item.quantity
        ratings[product.id] = 0 if rating_count == 0 else rating_total/rating_count
        sold_cnt[product.id] = product.order_items.filter(order__paid='8').aggregate(Sum('quantity'))['quantity__sum']
        sold_cnt[product.id] = 0 if sold_cnt[product.id] is None else sold_cnt[product.id]

    context = {
        'category': category,
        'categories': categories,
        'products': products,
        'ratings': ratings,
        'sold_cnt': sold_cnt,
        # 'crypto_data': crypto_data,
        'countries': countries,
        'form': form,
        'new_message': message,
    }

    return render(request, 'main/product/list.html', context)


def get_client_ip(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')


def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    product_stock = cart_product_form.get_product_stock(id)
    categories = Category.objects.all()
    crypto_data = crypto_currencies()
    message = len(Message.objects.filter(check=False))

    product_vendor = Product.objects.values('productOwnerID', 'country').get(id=id)
    country = countries.name(product_vendor.get('country'))
    product_vendor = product_vendor.get('productOwnerID')

    vendor = User.objects.values('id', 'username').filter(id=product_vendor, vendor=True)
    term_conditions = VendorTerm.objects.filter(userId=product_vendor)

    rating_total = 0
    rating_count = 0
    for order_item in product.order_items.filter(order__paid='8'):
        for rating in order_item.ratings.all():
            rating_total += rating.total * order_item.quantity
            rating_count += rating.count * order_item.quantity

    context = {
        'product': product,
        'categories': categories,
        'cart_product_form': cart_product_form,
        'product_stock': product_stock,
        'vendor': vendor[0],
        'avg_rating': 0 if rating_count == 0 else rating_total/rating_count,
        'country': country,
        'crypto_data': crypto_data,
        'new_message': message,
        'term_conditions': term_conditions[0]
    }
    return render(request, 'main/product/detail.html', context)


def search(request):
    if request.method == 'GET':
        message = len(Message.objects.filter(check=False))
        price = 0
        if request.GET.get('price'):
            price = int(request.GET.get('price'))

        country = request.GET.get('country', None)
        category = request.GET.get('category', None)
        category_id = Category.objects.filter(name=category)
        products = {}

        if price > 0 and category is '' and country is '':
            products = Product.objects.filter(Q(price__gte=price))
        elif category and price is 0 and country is '':
            print("===================================")
            products = Product.objects.filter(category__in=category_id)
        elif country and price is 0 and category is '':
            products = Product.objects.filter(country=country)
        elif price > 0 and category and country is '':
            products = Product.objects.filter(Q(price__gte=price), category__in=category_id)
        elif country and price > 0 and category is '':
            products = Product.objects.filter(Q(price__gte=price), country=country)
        elif country and category and price is 0:
            products = Product.objects.filter(country=country, category__in=category_id)
        elif price > 0 and category and country:
            products = Product.objects.filter(Q(price__gte=price), category__in=category_id, country=country)
        elif price is 0 and category is '' and country is '':
            products = Product.objects.all

        categories = Category.objects.all()
        # cryptocurrenies Data
        crypto_data = crypto_currencies()

        context = {
            'category': category,
            'categories': categories,
            'products': products,
            'crypto_data': crypto_data,
            'countries': countries,
            'new_message': message

        }
    else:
        raise Exception("405")
    return render(request, 'main/product/list.html', context)


# User Notification page
class UserMessageListView(LoginRequiredMixin, ListView):
    template_name = 'message/message_list.html'
    context_object_name = "messages"

    def get_queryset(self):
        admin_ids = User.objects.filter(admin=True)
        return Message.objects.filter(Q(sender__in=admin_ids) & Q(receiver=self.request.user)).order_by('-create')


# User Inbox page
class UserInboxListView(LoginRequiredMixin, ListView):
    template_name = 'inbox/inbox_list.html'
    context_object_name = "messages"

    def get_queryset(self):
        return Message.objects.filter((Q(sender=self.request.user) & Q(sender_removed=False)) |
                                      (Q(receiver=self.request.user) & Q(receiver_removed=False))).order_by('-create')
               #| Message.objects.filter(sender=self.request.user)


# User Inbox Send page
def inbox_send(request, receiver_id = '0'):
    if request.method == 'POST':
        obj = Message()
        obj.sender_id = request.user.id
        obj.receiver_id = request.POST.get('receiver_id')
        obj.content = request.POST.get('content')
        obj.save()

        msg = "Message sent successfully"
        messages.success(request, msg)
        return redirect("inbox_send")
    else:
        users = User.objects.all
        context_object = {'users': users, 'receiver_id': int(receiver_id)}
    return render(request, 'inbox/inbox_send.html', context_object)


# User Inbox Delete Message
def delete_message(request, message_id=''):
    message = Message.objects.get(pk=message_id)
    message_object = Message.objects.filter(id=message_id)

    if message.sender_id == request.user.id:
        message_object.update(sender_removed=True)
    elif message.receiver_id == request.user.id:
        message_object.update(receiver_removed=True)

    msg = "Message is deleted"
    messages.success(request, msg)
    return redirect("inbox_list")

main/templates/add_product.html
{% extends 'main/base.html' %}
{% load static %}
{% load widget_tweaks %}
{% load ratings %}
{% load auth_extras %}
{% load avatar_tags %}
{% block title %}
    Vendor Panel
{% endblock %}
{% block content %}
<div id="sidebar" class="span3">
    <div class="box text-center " style="background: #141414">
            <div class="p-a-md">
                {% avatar user 240 class="img-circle img-responsive" id="user_avatar" %}
                <p class="text-lg text-white block">{{ user.username }}</p>
                <p class="text-md text-accent">{{ user.level }}</p>
                {% comment %}<div class="profile-userbuttons">
                    <button type="button" class="btn btn-success btn-sm">Follow</button>
                    <button type="button" class="btn btn-danger btn-sm">Message</button>
                </div>{% endcomment %}
            </div>
            <div class="row b-t ">
                <div class="col-xs-4 m-a-sm " style="color: #6ec2d1">
					    <a href="{% url 'user_profile' %}">
                                    <i class="fa fa-home"></i>
                                    Overview </a>
                </div>
                {% if request.user|is_vendor %}
                <div class="col-xs-4 m-a-sm text-warn" >
                                <a href="{% url 'user_vendor_listProducts' %}">
                                    <i class="fa fa-user"></i>
                                    Vendor Panel </a>
                </div>
                {% else %}
                <div class="col-xs-4 m-a-sm {% if request.path == '/account/settings/' %} text-warn {% else %} text-side {% endif %}">
                                <a href="{% url 'user_favorites' %}">
                                    <i class="fa fa-thumbs-up"></i>
                                    My Favorites</a>
                </div>
                {% endif %}
                <div class="col-xs-4 m-a-sm " style="color: #6ec2d1">
                                <a href="{% url 'user_order_list' %}">
                                    <i class="fa fa-shopping-cart"></i>
                                    My Orders </a>
                </div>
                <div class="col-xs-4 m-a-sm {% if request.path == '/account/help/' %} text-warn {% else %} text-side {% endif %}">
                    <a href="{% url 'shipping_options' %}">
                        <i class="fa fa-ship"></i>
                        Shipping </a>
                </div>
                <div class="col-xs-4 m-a-sm" style="color: #6ec2d1">
                                <a href="{% url 'user_ratings' %}">
                                    <i class="fa fa-tasks"></i>
                                    My Ratings </a>
                </div>
                <div class="col-xs-4 m-a-sm" style="color: #6ec2d1">
                                <a href="#">
                                    <i class="fa fa-question"></i>
                                    Help </a>
                </div>
            </div>
        </div>
    <div class="" style="margin-bottom: 20px">
        <p class="side-header"> My Sales</p>
        <ul class="side-back" style="margin-top: -16px">
            <li class="side-content">
                <a href="{% url 'user_vendor_listProducts' %}" style="color: #6ec2d1">My Products</a>
            </li>
            <li class="side-content">
                <a href="{% url 'vendor_list_new_order' %}" style="color: #6ec2d1">New Orders</a>
            </li>
            <li class="side-content">
                <a href="{% url 'vendor_list_ship_order' %}" style="color: #6ec2d1">Shipped Orders</a>
            </li>
            <li class="side-content">
                <a href="{% url 'vendor_list_complete_order' %}" style="color: #6ec2d1">Completed Orders</a>
            </li>
            <li class="side-content">
                <a href="{% url 'vendor_list_cancel_order' %}" style="color: #6ec2d1">Canceled Orders</a>
            </li>
            <li class="side-content">
                <a href="{% url 'vendor_list_dispute_order' %}" style="color: #6ec2d1">Disputed Orders</a>
            </li>

        </ul>
    </div>
    {% comment %}<div class="" style="margin-bottom: 20px">
        <p class="side-header"> Products</p>
        <ul class="side-back" style="margin-top: -16px">
            <li class="side-content">
                <a href="" style="color: #6ec2d1">Add Products</a>
            </li>
        </ul>
    </div>{% endcomment %}

</div>

<div class="span9">
    <div class="well well-small" style="background-color: #0d0d0d; border: none">
        <div class="row-fluid">
            <div class="box" style="background: #141414; color: #666">
                <div class="box-header">
                    <h2 style="color: #6ec2d1">Add Products
                        {% comment %}<a href="{% url '' %}" ><span class="fa fa-plus text-warn m-b-md pull-right" style="font-size: 18px;">Add</span></a>{% endcomment %}
                    </h2>
                </div>
                <div class="box-divider m-0"></div>
                <div class="box-body">
                    <form action="{% url 'user_vendor_save_product'%}" method="post" enctype="multipart/form-data">{% csrf_token %}
                        <div class="form-group">
                            <label >Category:</label>
                            {{ form.category }}
                        </div>
                        <div class="form-group">
                            <label >Name:</label>
                            {{ form.name }}
                        </div>
                        <div class="form-group">
                            <label >Slug:</label>
                            {{ form.slug }}
                        </div>
                        <div class="form-group">
                            <label >Description:</label>
                            {{ form.description }}
                        </div>

                        <div class="form-group">
                            <label >Price:</label>
                            {{ form.price }}
                        </div>
                        <div class="form-group">
                            <label >Available:</label>
                            {{ form.available }}
                        </div>
                        <div class="form-group">
                            <label >Stock:</label>
                            {{ form.stock }}
                        </div>
                        <div class="form-group">
                            <label >PayOut Address:</label>
                            {{ form.payout_address }}
                        </div>
                        <div class="form-group">
                            <label >Image:</label>
                            {{ form.image }}
                        </div>
                        <div class="form-group">
                            <label >Country:</label>
                            {{ form.country }}
                        </div>
                        <input type="hidden" value="{{ owner_id }}" name="productOwnerID" id="id_productOwnerID">
                        <button  type="submit" class="btn btn-success">Save</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

main/templates/star_rating.html
{% extends "star_ratings/widget_base.html" %}
{% block rating_detail %}
{% endblock %}

main/templates/update_product.html
{% extends 'main/base.html' %}
{% load static %}
{% load widget_tweaks %}
{% load ratings %}
{% load auth_extras %}
{% load avatar_tags %}
{% block title %}
    Vendor Panel | Update Product
{% endblock %}
{% block content %}
<div id="sidebar" class="span3">
    <div class="box text-center " style="background: #141414">
            <div class="p-a-md">
                {% avatar user 240 class="img-circle img-responsive" id="user_avatar" %}
                <p class="text-lg text-white block">{{ user.username }}</p>
                <p class="text-md text-accent">{{ user.level }}</p>
                {% comment %}<div class="profile-userbuttons">
                    <button type="button" class="btn btn-success btn-sm">Follow</button>
                    <button type="button" class="btn btn-danger btn-sm">Message</button>
                </div>{% endcomment %}
            </div>
            <div class="row b-t ">
                <div class="col-xs-4 m-a-sm " style="color: #6ec2d1">
					    <a href="{% url 'user_profile' %}">
                                    <i class="fa fa-home"></i>
                                    Overview </a>
                </div>
                {% if request.user|is_vendor %}
                <div class="col-xs-4 m-a-sm text-warn" >
                                <a href="{% url 'user_vendor_listProducts' %}">
                                    <i class="fa fa-user"></i>
                                    Vendor Panel </a>
                </div>
                {% else %}
                <div class="col-xs-4 m-a-sm {% if request.path == '/account/settings/' %} text-warn {% else %} text-side {% endif %}">
                                <a href="{% url 'user_favorites' %}">
                                    <i class="fa fa-thumbs-up"></i>
                                    My Favorites</a>
                </div>
                {% endif %}
                <div class="col-xs-4 m-a-sm " style="color: #6ec2d1">
                                <a href="{% url 'user_order_list' %}">
                                    <i class="fa fa-shopping-cart"></i>
                                    My Orders </a>
                </div>
                <div class="col-xs-4 m-a-sm" style="color: #6ec2d1">
                                <a href="#">
                                    <i class="fa fa-tasks"></i>
                                    Tasks </a>
                </div>
                <div class="col-xs-4 m-a-sm" style="color: #6ec2d1">
                                <a href="#">
                                    <i class="fa fa-question"></i>
                                    Help </a>
                </div>
            </div>
        </div>
    <div class="" style="margin-bottom: 20px">
        <p class="side-header"> My Sales</p>
        <ul class="side-back" style="margin-top: -16px">
            <li class="side-content">
                <a href="{% url 'user_vendor_listProducts' %}" style="color: #6ec2d1">My Products</a>
            </li>
            <li class="side-content">
                <a href="{% url 'vendor_list_new_order' %}" style="color: #6ec2d1">New Orders</a>
            </li>
            <li class="side-content">
                <a href="{% url 'vendor_list_ship_order' %}" style="color: #6ec2d1">Shipped Orders</a>
            </li>
            <li class="side-content">
                <a href="{% url 'vendor_list_complete_order' %}" style="color: #6ec2d1">Completed Orders</a>
            </li>
            <li class="side-content">
                <a href="{% url 'vendor_list_cancel_order' %}" style="color: #6ec2d1">Canceled Orders</a>
            </li>
            <li class="side-content">
                <a href="{% url 'vendor_list_dispute_order' %}" style="color: #6ec2d1">Disputed Orders</a>
            </li>

        </ul>
    </div>
    {% comment %}<div class="" style="margin-bottom: 20px">
        <p class="side-header"> Products</p>
        <ul class="side-back" style="margin-top: -16px">
            <li class="side-content">
                <a href="" style="color: #6ec2d1">Add Products</a>
            </li>
        </ul>
    </div>{% endcomment %}

</div>

<div class="span9">
    <div class="well well-small" style="background-color: #0d0d0d; border: none">
        <div class="row-fluid">
            <div class="box" style="background: #141414; color: #666">
                <div class="box-header">
                    <h2 style="color: #6ec2d1">Add Products
                        {% comment %}<a href="{% url '' %}" ><span class="fa fa-plus text-warn m-b-md pull-right" style="font-size: 18px;">Add</span></a>{% endcomment %}
                    </h2>
                </div>
                <div class="box-divider m-0"></div>
                <div class="box-body">
                    <form action="{% url 'user_vendor_updateProduct' %}" method="post" enctype="multipart/form-data">{% csrf_token %}
                        <div class="form-group">
                            <label >Category:</label>
                            {{ form.category }}
                        </div>
                        <div class="form-group">
                            <label >Name:</label>
                            {{ form.name }}
                        </div>
                        <div class="form-group">
                            <label >Slug:</label>
                            {{ form.slug }}
                        </div>
                        <div class="form-group">
                            <label >Description:</label>
                            {{ form.description }}
                        </div>

                        <div class="form-group">
                            <label >Price:</label>
                            {{ form.price }}
                        </div>
                        <div class="form-group">
                            <label >Available:</label>
                            {{ form.available }}
                        </div>
                        <div class="form-group">
                            <label >Stock:</label>
                            {{ form.stock }}
                        </div>
                        <div class="form-group">
                            <label >PayOut Address:</label>
                            {{ form.payout_address }}
                        </div>
                        <div class="form-group">
                            <label >Image:</label>
                            {{ form.image }}
                        </div>
                        <div class="form-group">
                            <label >Country:</label>
                            {{ form.country }}
                        </div>
                        <input type="hidden" value="{{ owner_id }}" name="productOwnerID" id="id_productOwnerID">
                        <input type="hidden" value="{{ product_id }}" name="productID" id="id_productID">
                        <button  type="submit" class="btn btn-success">Save</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}